[build]
  publish = "."
  command = "node scripts/generate-config.js"

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/app.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/style.css"
  [headers.values]
    Cache-Control = "no-cache"
